# Generated by Django 6.0.1 on 2026-02-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0002_ride_proposer_alter_ride_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='vehicule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
