# Generated by Django 6.0.1 on 2026-02-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0003_ride_vehicule'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
