# Generated by Django 6.0.1 on 2026-02-23 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0004_ride_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ridebooking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='PENDING', max_length=10),
        ),
    ]
