# Generated by Django 6.0.1 on 2026-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0006_alter_ride_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('FULL', 'Full'), ('COMPLETED', 'Completed'), ('IN_PROGRESS', 'In Progress'), ('PROPOSED', 'Proposed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20),
        ),
    ]
