# Generated by Django 6.0.1 on 2026-03-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0008_taxi_servicetaxi'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxi',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='location_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='taxi',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
