# Generated by Django 6.0.1 on 2026-03-02 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0009_rename_fk_user_taxi_driver_taxi_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetaxi',
            name='driver',
        ),
    ]
