# Generated by Django 6.0.1 on 2026-03-06

import ride.models
import secrets
from django.db import migrations, models


def populate_share_codes(apps, schema_editor):
    Ride = apps.get_model('ride', 'Ride')

    for ride in Ride.objects.filter(share_code__isnull=True):
        share_code = secrets.token_hex(8)

        while Ride.objects.filter(share_code=share_code).exists():
            share_code = secrets.token_hex(8)

        ride.share_code = share_code
        ride.save(update_fields=['share_code'])


def noop_reverse(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0011_state_rename_taxi_driver_and_add_ride_route_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='share_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
        migrations.RunPython(populate_share_codes, reverse_code=noop_reverse),
        migrations.AlterField(
            model_name='ride',
            name='share_code',
            field=models.CharField(db_index=True, default=ride.models.generate_share_code, editable=False, max_length=32, unique=True),
        ),
    ]
