# Generated by Django 6.0.1 on 2026-03-19 10:39

from django.db import migrations, models
from django.utils import timezone


def populate_ridebooking_updated_at(apps, schema_editor):
    RideBooking = apps.get_model('ride', 'RideBooking')
    RideBooking.objects.filter(updated_at__isnull=True).update(updated_at=timezone.now())


class Migration(migrations.Migration):

    dependencies = [
        ('ride', '0013_ridebooking_updated_at'),
    ]

    operations = [
        migrations.RunPython(populate_ridebooking_updated_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ridebooking',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
            preserve_default=False,
        ),
    ]
