# Generated by Django 6.0.1 on 2026-03-02 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_recipient'),
        ('ride', '0010_rename_taxi_fk_user_remove_servicetaxi_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='service_taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='ride.servicetaxi'),
        ),
    ]
